name: Build LaTeX documents

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile BCCA 2021 paper
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./bcca_2021
          root_file: 000_main.tex
      - name: Compile Cluster Computing paper
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./cluster_computing
          root_file: 000_main.tex
      - name: Check pdf files
        run: |
          file bcca_2021/000_main.pdf | grep -q ' PDF '
          file cluster_computing/000_main.pdf | grep -q ' PDF '
      - name: Rename pdf files
        run: |
          mv bcca_2021/000_main.pdf bcca_2021/bcca_2021.pdf
          mv cluster_computing/000_main.pdf cluster_computing/cluster_computing.pdf
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: papers_and_presentations
          path: |
            bcca_2021/bcca_2021.pdf
            cluster_computing/cluster_computing.pdf
            presentation/bcca_2021_presentation.pdf
        if: always()
