name: Build LaTeX documents

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 000_generics.tex
      - name: Check pdf files
        run: |
          file 000_generics.pdf | grep -q ' PDF '
      - rename: Rename pdf files
        run: |
	  mv 000_generics.pdf generics.pdf
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: generics
          path: |
            generics.pdf
        if: always()
